FROM arm64v8/alpine:3.15@sha256:c74f1b1166784193ea6c8f9440263b9be6cae07dfe35e32a5df7a31358ac2060

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Alpine"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/alpine"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/alpine"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/alpine"

ARG REG_VERSION
ARG RETRY_VERSION

# renovate: datasource=github-releases depName=genuinetools/reg
ENV REG_VERSION="${REG_VERSION:-v0.16.1}"
# renovate: datasource=github-releases depName=owncloud-ci/retry
ENV RETRY_VERSION="${RETRY_VERSION:-v2.0.0}"

ENV TERM xterm

RUN apk --update add --no-cache \
      ca-certificates \
      bash \
      vim \
      curl \
      wget \
      bzip2 \
      unzip \
      ncurses \
      tar \
      shadow \
      su-exec \
      jq \
      git \
      make \
      rsync \
      tree \
      mailcap && \
    curl -SsL -o /usr/local/bin/reg "https://github.com/genuinetools/reg/releases/download/v${REG_VERSION##v}/reg-linux-arm64" && \
    curl -SsL -o /usr/local/bin/retry "https://github.com/owncloud-ci/retry/releases/download/v${RETRY_VERSION##v}/retry" && \
    chmod 755 /usr/local/bin/reg && \
    chmod 755 /usr/local/bin/retry && \
    rm -rf /var/cache/apk/* /tmp/*

COPY ./rootfs /
CMD ["bash"]
