FROM alpine:3.13@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Alpine"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/alpine"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/alpine"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/alpine"

ENV TERM xterm

RUN apk update && \
    apk upgrade && \
    apk add \
      ca-certificates \
      bash \
      vim \
      curl \
      wget \
      bzip2 \
      unzip \
      ncurses \
      tar \
      shadow \
      su-exec \
      jq \
      git \
      make \
      rsync \
      tree && \
    rm -rf /var/cache/apk/*

COPY ./rootfs /
CMD ["bash"]
