FROM regclient/regctl:v0.9.0@sha256:964add1616f41191761ca449a83f7afabf206a631b0f4f3319ac8e60e3b98070 as regctl

FROM arm64v8/alpine:3.22@sha256:d7641d4e055534bdac03070d3223d064999a9f2296598ec5122b66ceec18887b

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Alpine"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/alpine"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/alpine"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/alpine"

ARG REG_VERSION
ARG RETRY_VERSION
ARG HELM_VERSION

# renovate: datasource=github-releases depName=genuinetools/reg
ENV REG_VERSION="${REG_VERSION:-v0.16.1}"
# renovate: datasource=github-releases depName=owncloud-ci/retry
ENV RETRY_VERSION="${RETRY_VERSION:-v2.0.0}"
# renovate: datasource=github-tags depName=helm/helm
ENV HELM_VERSION="${HELM_VERSION:-v3.18.5}"

ENV TERM xterm

RUN apk --update add --no-cache \
      ca-certificates \
      coreutils \
      bash \
      vim \
      curl \
      wget \
      bzip2 \
      unzip \
      ncurses \
      tar \
      shadow \
      su-exec \
      jq \
      git \
      make \
      rsync \
      tree \
      mailcap && \
    curl -SsfL -o /usr/local/bin/reg "https://github.com/genuinetools/reg/releases/download/v${REG_VERSION##v}/reg-linux-arm64" && \
    curl -SsfL -o /usr/local/bin/retry "https://github.com/owncloud-ci/retry/releases/download/v${RETRY_VERSION##v}/retry" && \
    curl -SsfL "https://get.helm.sh/helm-v${HELM_VERSION##v}-linux-arm64.tar.gz" | tar xz --strip-components=1 -C /usr/local/bin linux-arm64/helm && \
    chmod 755 /usr/local/bin/reg && \
    chmod 755 /usr/local/bin/retry && \
    chmod 755 /usr/local/bin/helm && \
    rm -rf /var/cache/apk/* /tmp/*

COPY ./rootfs /
COPY --from=regctl /regctl /usr/local/bin/regctl

CMD ["bash"]
