FROM arm32v7/alpine:3.13@sha256:9663906b1c3bf891618ebcac857961531357525b25493ef717bca0f86f581ad6

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Alpine"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/alpine"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/alpine"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/alpine"

ARG REG_VERSION

# renovate: datasource=github-releases depName=genuinetools/reg
ENV REG_VERSION="${REG_VERSION:-0.16.0}"

ENV TERM xterm

RUN apk --update add --no-cache \
      ca-certificates \
      bash \
      vim \
      curl \
      wget \
      bzip2 \
      unzip \
      ncurses \
      tar \
      shadow \
      su-exec \
      jq \
      git \
      make \
      rsync \
      tree && \
    curl -SsL -o /usr/local/bin/reg "https://github.com/genuinetools/reg/releases/download/v${REG_VERSION}/reg-linux-arm" && \
    chmod 755 /usr/local/bin/reg && \
    rm -rf /var/cache/apk/* /tmp/*

COPY ./rootfs /
CMD ["bash"]
