FROM regclient/regctl:v0.5.0@sha256:ea769f114d072cc4dee5dc2104044590bc1db3bb7bb67b62e35adbab126517d5 as regctl

FROM alpine:3.18@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Alpine"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/alpine"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/alpine"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/alpine"

ARG REG_VERSION
ARG RETRY_VERSION
ARG HELM_VERSION

# renovate: datasource=github-releases depName=genuinetools/reg
ENV REG_VERSION="${REG_VERSION:-v0.16.1}"
# renovate: datasource=github-releases depName=owncloud-ci/retry
ENV RETRY_VERSION="${RETRY_VERSION:-v2.0.0}"
# renovate: datasource=github-tags depName=helm/helm
ENV HELM_VERSION="${HELM_VERSION:-v3.12.1}"

ENV TERM xterm

RUN apk --update add --no-cache \
      ca-certificates \
      coreutils \
      bash \
      vim \
      curl \
      wget \
      bzip2 \
      unzip \
      ncurses \
      tar \
      shadow \
      su-exec \
      jq \
      git \
      make \
      rsync \
      tree \
      yamllint \
      mailcap && \
    curl -SsfL -o /usr/local/bin/reg "https://github.com/genuinetools/reg/releases/download/v${REG_VERSION##v}/reg-linux-amd64" && \
    curl -SsfL -o /usr/local/bin/retry "https://github.com/owncloud-ci/retry/releases/download/v${RETRY_VERSION##v}/retry" && \
    curl -SsfL "https://get.helm.sh/helm-v${HELM_VERSION##v}-linux-amd64.tar.gz" | tar xz --strip-components=1 -C /usr/local/bin linux-amd64/helm && \
    chmod 755 /usr/local/bin/reg && \
    chmod 755 /usr/local/bin/retry && \
    chmod 755 /usr/local/bin/helm && \
    rm -rf /var/cache/apk/* /tmp/*

COPY ./rootfs /
COPY --from=regctl /regctl /usr/local/bin/regctl

CMD ["bash"]
