FROM arm32v7/alpine:3.17@sha256:4c679bd1e6b6516faf8466986fc2a9f52496e61cada7c29ec746621a954a80ac

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Alpine"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/alpine"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/alpine"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/alpine"

ARG REG_VERSION
ARG RETRY_VERSION
ARG HELM_VERSION

# renovate: datasource=github-releases depName=genuinetools/reg
ENV REG_VERSION="${REG_VERSION:-v0.16.1}"
# renovate: datasource=github-releases depName=owncloud-ci/retry
ENV RETRY_VERSION="${RETRY_VERSION:-v2.0.0}"
# renovate: datasource=github-tags depName=helm/helm
ENV HELM_VERSION="${HELM_VERSION:-v3.10.3}"

ENV TERM xterm

RUN apk --update add --no-cache \
      ca-certificates \
      bash \
      vim \
      curl \
      wget \
      bzip2 \
      unzip \
      ncurses \
      tar \
      shadow \
      su-exec \
      jq \
      git \
      make \
      rsync \
      tree \
      mailcap && \
    curl -SsfL -o /usr/local/bin/reg "https://github.com/genuinetools/reg/releases/download/v${REG_VERSION##v}/reg-linux-arm" && \
    curl -SsfL -o /usr/local/bin/retry "https://github.com/owncloud-ci/retry/releases/download/v${RETRY_VERSION##v}/retry" && \
    curl -SsfL "https://get.helm.sh/helm-v${HELM_VERSION##v}-linux-arm.tar.gz" | tar xz --strip-components=1 -C /usr/local/bin linux-arm/helm && \
    chmod 755 /usr/local/bin/reg && \
    chmod 755 /usr/local/bin/retry && \
    chmod 755 /usr/local/bin/helm && \
    rm -rf /var/cache/apk/* /tmp/*

COPY ./rootfs /
CMD ["bash"]
